### ISSUE TITLE
Error: `Case._repr_pretty_() missing 1 required positional argument: 'cycle'`

### ISSUE THREAD

**Issue by flashcode** [HypothesisWorks/hypothesis#4151]
Hi,

Following my previous performance issue #4139 (which is now solved, thanks!), I'm facing another issue with the release 6.115.6, I get this error:

```
Case._repr_pretty_() missing 1 required positional argument: 'cycle'
```

This is a regression in the version 6.115.6: it works fine with 6.115.5.

Output of schemathesis:

```
Base URL: http://127.0.0.1:9000/api
Specification version: Open API 3.1.0
Random seed: 111647138045842794258613564325217735102
Workers: 1
Collected API operations: 15
Collected API links: 0
API probing: ERROR
Schema analysis: SKIP

POST /api/handshake .                                                                     [  6%]
GET /api/version .                                                                        [ 13%]
GET /api/buffers .                                                                        [ 20%]
GET /api/buffers/{buffer_id} .                                                            [ 26%]
GET /api/buffers/{buffer_name} E                                                          [ 33%]
GET /api/buffers/{buffer_id}/lines .                                                      [ 40%]
GET /api/buffers/{buffer_id}/lines/{line_id} .                                            [ 46%]
GET /api/buffers/{buffer_name}/lines E                                                    [ 53%]
GET /api/buffers/{buffer_name}/lines/{line_id} E                                          [ 60%]
GET /api/buffers/{buffer_id}/nicks .                                                      [ 66%]
GET /api/buffers/{buffer_name}/nicks E                                                    [ 73%]
GET /api/hotlist .                                                                        [ 80%]
POST /api/input E                                                                         [ 86%]
POST /api/ping E                                                                          [ 93%]
POST /api/sync E                                                                          [100%]

============================================ ERRORS ============================================
________________________________ GET /api/buffers/{buffer_name} ________________________________
Runtime Error

Case._repr_pretty_() missing 1 required positional argument: 'cycle'
_____________________________ GET /api/buffers/{buffer_name}/lines _____________________________
Runtime Error

Case._repr_pretty_() missing 1 required positional argument: 'cycle'
________________________ GET /api/buffers/{buffer_name}/lines/{line_id} ________________________
Runtime Error

Case._repr_pretty_() missing 1 required positional argument: 'cycle'
_____________________________ GET /api/buffers/{buffer_name}/nicks _____________________________
Runtime Error

Case._repr_pretty_() missing 1 required positional argument: 'cycle'
_______________________________________ POST /api/input ________________________________________
Runtime Error

Case._repr_pretty_() missing 1 required positional argument: 'cycle'
________________________________________ POST /api/ping ________________________________________
Runtime Error

Case._repr_pretty_() missing 1 required positional argument: 'cycle'
________________________________________ POST /api/sync ________________________________________
Runtime Error

Case._repr_pretty_() missing 1 required positional argument: 'cycle'
_______________________________________ API Probe errors _______________________________________
Network Error

HTTPConnectionPool(host='127.0.0.1', port=9000): Read timed out. (read timeout=10.0)

Add this option to your command line parameters to see full tracebacks: --show-trace

Need more help?
    Join our Discord server: https://discord.gg/R9ASRAmHnA
=========================================== SUMMARY ============================================

Performed checks:
    not_a_server_error                              800 / 800 passed          PASSED 
    status_code_conformance                         800 / 800 passed          PASSED 
    content_type_conformance                        800 / 800 passed          PASSED 
    response_headers_conformance                    800 / 800 passed          PASSED 
    response_schema_conformance                     800 / 800 passed          PASSED 
    negative_data_rejection                         800 / 800 passed          PASSED 
    ignored_auth                                    800 / 800 passed          PASSED 

Experimental Features:
  - OpenAPI 3.1: Support for response validation
    Feedback: https://github.com/schemathesis/schemathesis/discussions/1822

Your feedback is crucial for experimental features. Please visit the provided URL(s) to share your thoughts.

Tip: Use the `--report` CLI option to visualize test results via Schemathesis.io.
We run additional conformance checks on reports from public repos.

================================ 8 passed, 7 errored in 17.10s =================================
```

**Comment by Stranger6667** [comment]
Issue in Schemathesis- https://github.com/schemathesis/schemathesis/issues/2565

**Comment by Stranger6667** [comment]
Fixed in Schemathesis `3.38.5`

On the Hypothesis side - It seems like the original change wasn't equivalent in the sense of handling of the `_repr_pretty_` method. I.e. in stateful tests the old calling convention still works for structures used for code sample generation, but outside of stateful testing, dataclasses will give an error mentioned in this issue.

**Comment by flashcode** [comment]
Thanks @Stranger6667, so the issue was on schemathesis side, and this issue can be closed?
