### PR TITLE
Fix unimplemented default TypeVar argument in 3.13a4

### LINKED ISSUE #3916: TypeError on CPython 3.13 for 6.99.2
I got on CPython 3.13a4 (during collection of tests by pytest):
```
    /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/hypothesis/strategies/_internal/strategies.py:56: in <module>
        Ex = TypeVar("Ex", covariant=True, default=Any)
    E   TypeError: typevar() got an unexpected keyword argument 'default'
```
CI logs: https://github.com/skirpichev/gmpy/actions/runs/8227832838/job/22496350932

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Fix #3916
- The regression was introduced by #3915
- PEP 696 was accepted but is not currently implemented python/cpython#116129

also closes #3918 by cherry-picking

### CODE REVIEW

**Comment by Zac-HD** [comment]
Ah, looks like it's time to un-comment the py313 tests in `.github/workflows/main.yml` (and add nocover + niche) - they were disabled for the pre-alpha phase due to instability, but now that we're in alpha and getting issues about it, we can re-enable.

**Comment by JonathanPlasse** [comment]
I fix the remaining error and enable the CI for 3.13.
There are CI errors, but they seem unrelated to the changes of this PR.

**Comment by Zac-HD** [comment]
Thanks again @JonathanPlasse!  I'll push some skips for those tests and open an issue to follow up shortly 👍

**Review by Zac-HD — APPROVED** [review]
